// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWqNQxjTM8HX6s7wTjBKLRV32-l90nvGc',
    appId: '1:826813894309:web:6b1378cf02c66721d8c74c',
    messagingSenderId: '826813894309',
    projectId: 'workify-7c641',
    authDomain: 'workify-7c641.firebaseapp.com',
    storageBucket: 'workify-7c641.firebasestorage.app',
    measurementId: 'G-9MH4YW0NRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRxykE2YoDCMwWAwDbCi-nc1drvbhCSMc',
    appId: '1:826813894309:android:1e55502a93f87a18d8c74c',
    messagingSenderId: '826813894309',
    projectId: 'workify-7c641',
    storageBucket: 'workify-7c641.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJw6QuVOpzO2xBqjBi-rKDtPrX7KK2mq8',
    appId: '1:826813894309:ios:2737934dcacbe736d8c74c',
    messagingSenderId: '826813894309',
    projectId: 'workify-7c641',
    storageBucket: 'workify-7c641.firebasestorage.app',
    iosBundleId: 'com.example.buildgym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJw6QuVOpzO2xBqjBi-rKDtPrX7KK2mq8',
    appId: '1:826813894309:ios:2737934dcacbe736d8c74c',
    messagingSenderId: '826813894309',
    projectId: 'workify-7c641',
    storageBucket: 'workify-7c641.firebasestorage.app',
    iosBundleId: 'com.example.buildgym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWqNQxjTM8HX6s7wTjBKLRV32-l90nvGc',
    appId: '1:826813894309:web:f98f82b5849d802bd8c74c',
    messagingSenderId: '826813894309',
    projectId: 'workify-7c641',
    authDomain: 'workify-7c641.firebaseapp.com',
    storageBucket: 'workify-7c641.firebasestorage.app',
    measurementId: 'G-27PPDFQ7W5',
  );

}